# Generated by Django 2.2.1 on 2019-09-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='person',
        ),
        migrations.AddField(
            model_name='teacher',
            name='person',
            field=models.ManyToManyField(to='app01.Person'),
        ),
    ]
