# Generated by Django 2.2.1 on 2019-09-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20190915_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='num',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='book',
            name='saled',
            field=models.IntegerField(default=100),
        ),
    ]
