# Generated by Django 2.2.1 on 2019-09-16 11:54

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20190915_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('email', models.CharField(max_length=32, verbose_name='邮箱')),
            ],
            options={
                'verbose_name_plural': '作者表',
                'db_table': 'author',
                'verbose_name': '作者表',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=32, verbose_name='类型')),
                ('description', ckeditor.fields.RichTextField(verbose_name='描述')),
            ],
            options={
                'verbose_name_plural': '类型表',
                'db_table': 'type',
                'verbose_name': '类型表',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('date', models.DateField(auto_now=True)),
                ('content', ckeditor.fields.RichTextField(verbose_name='内容')),
                ('description', ckeditor.fields.RichTextField(verbose_name='描述')),
                ('picture', models.ImageField(upload_to='images')),
                ('recommend', models.IntegerField(default=0, verbose_name='推荐')),
                ('click', models.IntegerField(default=0, verbose_name='点击率')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app01.Author', verbose_name='作者')),
                ('type', models.ManyToManyField(to='app01.Type', verbose_name='类型')),
            ],
            options={
                'verbose_name_plural': '文章表',
                'db_table': 'article',
                'verbose_name': '文章表',
            },
        ),
    ]
